### ISSUE TITLE
Error calling method on NPObject

### ISSUE THREAD

**Issue by crissi** [felquis/ionic-cca#2]
Getting this error when calling any cordova plugin methods.

I am on android

**Comment by felquis** [comment]
Hi Crissi

This error is problably because cca automatically add cordova.js

In my case, i just removed The cordova.js call in index.html and everything
worked fine.

Em sábado, 22 de novembro de 2014, crissi notifications@github.com
escreveu:

> getting this when calling plugin methods
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/felquis/ionic-cca/issues/2.

## 

Felquis Gimenes - Front-end
felquis.com +55 011 95980 2233

**Comment by crissi** [comment]
Yes that does it. Thanks:)
